language: ruby
rvm:
  - 2.1
  - 2.0.0

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

script: bundle exec rake

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails4.1.gemfile